### ISSUE TITLE
Opening some USD files can crash Kraken.

### ISSUE THREAD

**Issue by Marti-S** [wabiverse/Kraken#12]
This bug usually occurs after a few times of opening different USD files.

<img width="1412" alt="Screenshot_2024-04-17_at_12 14 12" src="https://github.com/wabiverse/Kraken/assets/114810952/469fd63c-c51b-4629-91fe-c3af67abd62e">

**Comment by furby-tm** [comment]
@stackotter Also I am interested in getting this open source framework alternative to [SceneKit](https://developer.apple.com/documentation/scenekit/sceneview) working with each of [https://github.com/stackotter/swift-cross-ui](**SwiftCrossUI's**) backends, so that **SwiftUI** can be easily utilized in a same cross-platform way.

**Comment by Marti-S** [comment]
If I have a vote, I will vote yes for this proposal.

**Comment by stackotter** [comment]
I love the idea of HydraKit integrating with SwiftCrossUI, I've been waiting for an opportunity to figure out how 3rd party libraries can work with individual backends to provide new native views (and preferably without having to provide a separate target for each backend, but that may be the case for now).

> The question there is should this be apart of the **SwiftUSD** package, or in its own?

I reckon it should be separate, no one's ever gonna find out about anything if it's all in the monolithic SwiftUSD repo.

> Which especially for this use case, brings me to one additional nice feature improvement proposal for **SwiftCrossUI**, which is to implement an equivalent `DocumentGroup(newDocument:)` for that package (read more about this API [here](https://developer.apple.com/documentation/swiftui/documentgroup)), it would definitely help for use cases such as these.

That would definitely be nice to have, but it'll require quite a bit of platform-specific stuff for things like menus and file dialogs so I'll need to add support for those to the 3 main backends first.

**Comment by furby-tm** [comment]
I've looked into this issue further and pinned it down to TBB threading issues in SwiftUSD, resolved in [this revision of SwiftUSD](https://github.com/wabiverse/SwiftUSD/commit/4235044f2f5a664016011be4c8275ddb687f9201#diff-705d3e2f6bcce5f7a618ecc9aa9921f238479c6bc6c4eb9a1a6abf4ff86eac30).
